### ISSUE TITLE
В чем отличие for of и for in? И почему здесь и ниже for in?

### ISSUE THREAD

**Issue by frontgirl** [denver411/game_JS_final-task_netology#4]
https://github.com/denver411/game_JS_final-task_netology/blob/eb647c564b16295ba2b0ccfa6940cb0d3f4becb4/game.js#L252

**Comment by denver411** [comment]
in перебирает ключи
of значения
Здесь использовал in, чтобы заменить по ключу элемент массива

**Comment by frontgirl** [comment]
Переписывать массив - в данном случае не самая хорошая идея. Я бы рекомендовала использовать новую переменную для результата и записывать результат в нее, а оба for in замените на 2 forEach или map, внутри них также у вас будет доступ и к элементу, и к его индексу. Но можно обойтись и без индекса, если использовать push (разумеется, с новой переменной).

**Comment by denver411** [comment]
Разобрался вроде. Сейчас верно?
