### ISSUE TITLE
Массивы следует перебирать с помощью for of либо одного из перебирающих методов (например, forEach, map)

### ISSUE THREAD

**Issue by frontgirl** [denver411/game_JS_final-task_netology#6]
https://github.com/denver411/game_JS_final-task_netology/blob/eb647c564b16295ba2b0ccfa6940cb0d3f4becb4/game.js#L264

**Comment by denver411** [comment]
Изменил метод перебора массива на for in. Не могу понять, как вытащить координаты при применении for of

**Comment by frontgirl** [comment]
при for of - никак, чтобы вытащить координаты, используйте перебирающие методы forEach или map, в зависимости от цели цикла(forEach - для операции с каждым элементом массива, map - для создания нового массива, в котором каждый элемент - это элемент старого, преобразованный каким-то образом).

**Comment by denver411** [comment]
Проверьте пожалуйста, верно ли я сделал
